layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
      - ottg

social_media:
  linkedin: kylepw
  medium: kylepw
  twitter: kpw86

topics:
  - name: Python
    web_url: https://www.python.org
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/600px-Python-logo-notext.svg.png
  - name: Go
    web_url: https://golang.org
    image_url: https://miro.medium.com/max/1200/1*yh90bW8jL4f8pOTZTvbzqw.png
  - name: Docker
    web_url: https://www.docker.com
    image_url: https://www.getconvey.com/wp-content/uploads/2015/09/docker.png
  - name: PostgreSQL
    web_url: https://www.postgresql.org
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Postgresql_elephant.svg/1920px-Postgresql_elephant.svg.png
  - name: DevOps
  - name: Software Architecture & Design

theme: jekyll-theme-minimal